name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/C6502/C6502.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/C6502/C6502.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./tests/C6502.Tests/C6502.Tests.csproj
